source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RCView_Example', :exclusive => true do
  pod "RCView", :path => "../"
end

target 'RCView_Tests', :exclusive => true do
  pod "RCView", :path => "../"

  
end
